---
- name: Download pwch checksum file and signature
  ansible.builtin.get_url:
    url: |
      {{ pwch_base_url }}/{{ pwch_version }}/pwch_{{ pwch_arch }}.{{ item }}
    dest: "{{ ansible_env.HOME }}"
    force: true
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
  loop:
    - sha256
    - sha256.asc

- name: Copy public key to host
  ansible.builtin.copy:
    src: public.asc
    dest: "{{ ansible_env.HOME }}/public.asc"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0640"

- name: Import public key
  ansible.builtin.command: gpg --import {{ ansible_env.HOME }}/public.asc
  changed_when: false

- name: Verify checksum file
  ansible.builtin.command: >
    gpg --verify {{ ansible_env.HOME }}/pwch_{{ pwch_arch }}.sha256.asc
    {{ ansible_env.HOME }}/pwch_{{ pwch_arch }}.sha256
  register: verify
  changed_when: false
  failed_when: verify.rc != 0

- name: Read checksum file
  ansible.builtin.slurp:
    src: "{{ ansible_env.HOME }}/pwch_{{ pwch_arch }}.sha256"
  register: checksums

- name: Extract hashes
  ansible.builtin.set_fact:
    pwch_checksums: |
      {{ checksums['content'] | b64decode | regex_findall('[0-9a-f]{64}') }}
